lobby: graceful shutdown中のgame serverの情報を取得する
KLab/wsnet2 pull request #52
Opened 2023-06-26 10:43 UTC by methane

gameCache.Rand() は Running 状態のホストのみを返す。
gameCache.Get(hostID) は Closing 中のホストも返す。

2023-06-26 10:45 UTC, methane commented
まだコンパイル通っただけで動作確認まだです。

hubサーバーは再入室不許可のままにして、別の部屋から観戦するという理解でいいでしょうか？

2023-06-27 02:29 UTC, makiuchi-d commented
はい、そのとおりです。hubは別のhubから繋げば問題ないので現状通りでお願いします。

2023-06-27 10:42 UTC, methane commented
wsnet2-bot は動きました

雑談: macOS上のOrbStackで動かしてみましたが、
* bin/wsnet2-bot がLinuxバイナリになるのでmacから動かない。
* docker compose exec builder bin/wsnet2-bot をするとデフォルトのホスト設定が不味くて動かない。

という結果に。今回は rm bin/wsnet2-bot; make bin/wsnet2-bot; bin/wsnet2-bot で動かしました。

macOS + Docker Desktop (or OrbStack) で開発している人を助けるために、Makefile に docker compose exec を使って bot を動かすためのコマンドを追加するPRを後で別に作ります。

2023-06-27 13:28 UTC, makiuchi-d commented
Makefileはコンテナの中でmakeを呼ぶ用途で使っているので、そこにdockerコマンドを書くのはちぐはぐな気がしました。
compose.yamlにbotを動かす用のserviceをprofile指定して用意して、`docker compose run`するのが良いかもしれません。
（dashboardのfrontbuilderの要領）
そのためにbotのオプションでホストを指定できるようにもしないとです。
bot改修は別途進めているので、一旦issueに上げておいてもらえると助かります。

2023-07-04 11:56 UTC, makiuchi-d requested changes
1点だけコメントしました。
他は良さそうです。ありがとうございます。

2023-07-04 11:56 UTC, makiuchi-d commented on server/lobby/game_cache.go
> +		if s.Status == service.HostStatusRunning {
`game/service` をlobbyがimportするのは設計上よくないので、commonに移動お願いします。
hubでも同じHostStatus*を定義してたので、統一してしまいましょう

2023-07-04 12:19 UTC, makiuchi-d requested changes
もう一箇所、コメント内の単語だけ。

「接続」はwebsocketのことを指したくて、
ここでclosingも取得するのはjoinのためなので「入室」にしました。

2023-07-05 12:28 UTC, makiuchi-d approved these changes

2023-07-05 12:28 UTC, merged