server: MySQLを使ったテスト
KLab/wsnet2 pull request #53
Opened 2023-07-01 04:17 UTC by methane

2023-07-03 11:02 UTC, methane commented
#52 に対するテストを追加しました。 MySQLを立ち上げて単体テストを実行します。

2023-07-03 11:04 UTC, methane commented
https://github.com/KLab/wsnet2/blob/f44536703448622918ff7a66092febd72699dc04/server/lobby/main_test.go#L18-L26

2023-07-05 03:16 UTC, makiuchi-d commented
unit-testにDB使うの悩ましいけれど、他にやりようがないですよね
（sqlmockだとクエリが変わったときにテストも壊れるのがつらい

2023-07-05 03:17 UTC, makiuchi-d requested changes
ローカルでの実行も考慮されてて、テスト内容は良いと思います。ありがとうございます。
workflowsのyamlでの環境変数指定の場所だけ確認お願いします。

2023-07-07 08:33 UTC, makiuchi-d approved these changes

2023-07-07 08:55 UTC, merged